"""Interface-level constants for tasks CLI/TUI."""

TIMESTAMP_FORMAT = "%Y-%m-%d %H:%M"
GITHUB_GRAPHQL = "https://api.github.com/graphql"

AI_HELP = """apply_task — hardline rules for AI agents

1) Operate only via apply_task. Never edit .tasks/ directly. Track context via .last (TASK@domain).
2) Decompose: root task + nested subtasks (any depth). Every subtask: title ≥20 chars; success_criteria; tests; blockers. Checkpoints only through ok/note/bulk --path.
3) Create tasks: set domain (--domain/-F). Generate subtasks template (apply_task template subtasks --count N > .tmp/subtasks.json), fill criteria/tests/blockers. Create: apply_task create "Title #tags" --domain <d> --description "<what/why/acceptance>" --tests "<proj tests>" --risks "<proj risks>" --subtasks @.tmp/subtasks.json. Add nested: apply_task subtask TASK --add "<title>" --criteria "...;..." --tests "...;..." --blockers "...;..." --parent-path 0.1 (path like 0.1.2).
4) Maintain subtasks: add via subtask; checkpoints via ok --path X.Y (criteria/tests/blockers with notes); complete via subtask --done --path only if all checkpoints OK; note progress with note --path.
5) Statuses: start at fail -> warn when working -> ok only when all subtasks done. Commands: apply_task start/done/fail TASK.
6) Quality gates: diff coverage ≥85%; cyclomatic complexity ≤10; no mocks/stubs in prod; one file = one responsibility; prefer <300 LOC. Before delivery run pytest -q and log executed tests. Always keep explicit blockers/tests/criteria on every node.
7) GitHub Projects: config .apply_task_projects.yaml; token APPLY_TASK_GITHUB_TOKEN|GITHUB_TOKEN. If no token/remote, sync is off; CLI works offline.
Language: reply to user in their language unless asked otherwise. Task text/notes follow user language; code/tests/docs stay in English. Explicit blockers/tests/criteria on every node. No checkpoints — no done.
"""

LANG_PACK = {
    "en": {
        "TITLE": "TITLE",
        "SUBTASKS": "SUBTASKS",
        "SUBTASK_DETAILS": "SUBTASK DETAILS",
        "CRITERIA": "Criteria",
        "TESTS": "Tests",
        "BLOCKERS": "Blockers",
        "DESCRIPTION": "Description",
        "BLOCKERS_HEADER": "Blockers",
        "DOMAIN": "Domain",
        "PHASE": "Phase",
        "COMPONENT": "Component",
        "PARENT": "Parent",
        "DESCRIPTION_MISSING": "No description",
        "PRIORITY": "Priority",
        "PROGRESS": "Progress",
        "COMPLETED_SUFFIX": "done",
        "TAGS": "Tags",
        "STATUS_DONE": "DONE",
        "STATUS_IN_PROGRESS": "IN PROGRESS",
        "STATUS_BACKLOG": "BACKLOG",
        "CHECKPOINT_CRITERIA": "Criteria",
        "CHECKPOINT_TESTS": "Tests",
        "CHECKPOINT_BLOCKERS": "Blockers",
        "LOG_CRITERIA": "Criteria",
        "LOG_TESTS": "Tests",
        "LOG_BLOCKERS": "Blockers",
        "DESCRIPTION_PROMPT": "Description",
        "DOMAIN_LABEL": "Domain",
        "PHASE_LABEL": "Phase",
        "COMPONENT_LABEL": "Component",
        "TAGS_LABEL": "Tags",
        "PARENT_LABEL": "Parent",
        "BLOCKERS_LABEL": "Blockers",
        "LANGUAGE_LABEL": "Language",
        "LANGUAGE_HINT": "Enter — cycle language (en, ru, uk, es, fr, zh, hi, ar)",
        "CLIPBOARD_EMPTY": "Clipboard is empty or unavailable",
        "OPTION_DISABLED": "Option unavailable",
        "VALUE_NOT_AVAILABLE": "n/a",
        "ERR_TASK_NOT_COMPLETE": "Not all subtasks are done",
        "ERR_TASK_NO_CRITERIA_TESTS": "No success criteria/tests at task level",
        "ERR_SUBTASK_NO_CRITERIA": "Subtask {idx} '{title}' has no success criteria",
        "ERR_SUBTASK_NO_TESTS": "Subtask {idx} '{title}' has no tests",
        "ERR_SUBTASK_CHECKPOINTS": "Confirm {items} before completing",
        "STATUS_MESSAGE_PUSH_OK": "Git push completed",
        "STATUS_MESSAGE_PUSH_FAIL": "Push failed: {error}",
        "STATUS_MESSAGE_BOOTSTRAP_ERROR": "Git bootstrap error: {error}",
        "STATUS_MESSAGE_BOOTSTRAP_FAILED": "Git bootstrap failed: {error}",
        "STATUS_MESSAGE_REFRESHED": "Projects cache refreshed",
        "STATUS_MESSAGE_OPTION_DISABLED": "Option unavailable",
        "STATUS_MESSAGE_PAT_MISSING": "PAT missing",
        "STATUS_MESSAGE_PROMPT_PAT": "Enter PAT for validation",
        "STATUS_MESSAGE_RATE_LIMIT": "Rate limit: remaining {remaining}; wait {seconds}s",
        "STATUS_MESSAGE_CLI_UPDATED": "↻ CLI: tasks updated (external change)",
        "STATUS_MESSAGE_AUTO_SYNC": "Auto-sync: {count} tasks",
        "STATUS_MESSAGE_LANG_SET": "Language set to {lang}",
        "STATUS_MESSAGE_PAT_SAVED": "PAT saved",
        "STATUS_MESSAGE_PAT_CLEARED": "PAT cleared",
        "STATUS_MESSAGE_PROJECT_NUMBER_REQUIRED": "Project number must be a positive integer",
        "STATUS_MESSAGE_PROJECT_NUMBER_UPDATED": "Project number updated",
        "STATUS_MESSAGE_POOL_INTEGER": "Pool must be an integer (0=auto)",
        "STATUS_MESSAGE_POOL_UPDATED": "Pool size updated",
        "STATUS_MESSAGE_CHECKPOINTS_REQUIRED": "Checkpoints are not confirmed",
        "STATUS_MESSAGE_PROJECT_OPEN": "Opening GitHub Project → {url}",
        "STATUS_MESSAGE_OPEN_FAILED": "Could not open link: {error}",
        "STATUS_MESSAGE_PROJECT_URL_UNAVAILABLE": "Project URL unavailable",
        "STATUS_MESSAGE_PASTE_PAT": "Paste PAT (leave empty to clear)",
        "STATUS_MESSAGE_SYNC_ON": "Sync enabled",
        "STATUS_MESSAGE_SYNC_OFF": "Sync disabled",
        "STATUS_MESSAGE_VALIDATING": "Validating...",
        "STATUS_MESSAGE_VALIDATE_LABEL": "Validating {label}",
        "ERR_TASK_NOT_FOUND": "Task {task_id} not found",
        "SETTINGS_NAV_HINT": "Up/Down — select, Enter — action, Esc — close",
        "SETTINGS_STATUS_LABEL": "Sync status",
        "SETTINGS_STATUS_HINT": "Current sync availability",
        "SETTINGS_STATUS_ON": "Sync ON",
        "SETTINGS_STATUS_OFF": "Sync OFF ({reason})",
        "SETTINGS_PAT_LABEL": "GitHub PAT",
        "SETTINGS_PAT_SAVED": "Saved (…{preview})",
        "SETTINGS_PAT_ENV": "ENV {env}",
        "SETTINGS_PAT_NOT_SET": "Not set",
        "SETTINGS_PAT_HINT": "Enter — paste new PAT or leave empty to clear",
        "SETTINGS_SYNC_LABEL": "Sync",
        "SETTINGS_SYNC_HINT": "Enter — toggle auto-sync",
        "SETTINGS_SYNC_NO_REMOTE": "Unavailable (no git remote)",
        "SETTINGS_SYNC_DISABLED": "Disabled",
        "SETTINGS_SYNC_NO_PAT": "Unavailable (no PAT)",
        "SETTINGS_SYNC_ENABLED": "Enabled",
        "SETTINGS_PROJECT_LABEL": "GitHub Project",
        "SETTINGS_PROJECT_UNAVAILABLE": "unavailable",
        "SETTINGS_BOOTSTRAP_LABEL": "Initialize git + origin",
        "SETTINGS_BOOTSTRAP_VALUE": "Create repo and push",
        "SETTINGS_BOOTSTRAP_HINT": "Enter — provide URL (https://github.com/owner/repo.git); will run git init/add/push",
        "SETTINGS_PROJECT_URL_LABEL": "Project URL",
        "SETTINGS_PROJECT_URL_HINT": "g — open in browser",
        "SETTINGS_PROJECT_NUMBER_LABEL": "Project number",
        "SETTINGS_PROJECT_NUMBER_HINT": "Enter — update Project v2 number",
        "SETTINGS_POOL_LABEL": "Sync pool",
        "SETTINGS_POOL_HINT": "Enter — set sync pool size (0=auto). Limits API budget.",
        "SETTINGS_LAST_PULL_LABEL": "Last pull/push",
        "SETTINGS_LAST_PULL_HINT": "Updated after successful sync",
        "SETTINGS_RATE_LABEL": "Rate limit",
        "SETTINGS_RATE_HINT": "GitHub remaining/reset (updates after requests)",
        "SETTINGS_REMOTE_LABEL": "Git remote",
        "SETTINGS_REMOTE_HINT": "Used to auto-detect Projects; change via git remote set-url origin",
        "SETTINGS_REFRESH_LABEL": "Reload fields",
        "SETTINGS_REFRESH_VALUE": "Refresh GraphQL cache",
        "SETTINGS_REFRESH_HINT": "Enter — reset Projects fields cache before sync",
        "SETTINGS_REFRESH_DISABLED": "Need selected project and PAT",
        "SETTINGS_VALIDATE_PAT_LABEL": "Validate PAT",
        "SETTINGS_VALIDATE_PAT_HINT": "Enter — validate token via GitHub GraphQL",
        "SETTINGS_VALIDATE_PAT_DISABLED": "Save PAT first",
        "LABEL_SUBTASKS_JSON": "JSON array of subtasks",
        "ERR_INVALID_FOLDER": "Invalid folder path",
        "ERR_NO_LAST_TASK": "No last task: run apply_task show/list/next to set context",
        "ERR_JSON_ARRAY_REQUIRED": "JSON must be an array of objects",
        "ERR_JSON_ELEMENT_OBJECT": "Element {idx} must be an object",
        "ERR_JSON_ELEMENT_TITLE": "Element {idx} is missing 'title'",
        "ERR_JSON_ELEMENT_CRITERIA": "Element {idx}: provide at least one success criterion",
        "ERR_JSON_ELEMENT_TESTS": "Element {idx}: provide tests to verify",
        "ERR_JSON_ELEMENT_BLOCKERS": "Element {idx}: provide blockers/dependencies",
        "ERR_JSON_INVALID": "Invalid JSON: {error}",
        "ERR_JSON_FORMAT_HINT": "Use JSON array. Example: '[{\"title\":\"Design cache rollout >=20 chars\",\"criteria\":[\"hit ratio >80%\"],\"tests\":[\"pytest -k cache\"],\"blockers\":[\"redis downtime\"]}]'\\nReason: {error}",
        "ERR_FLAGSHIP_SUBTASKS": "Subtasks do not meet flagship quality",
        "PROMPT_ABORTED": "[X] Aborted",
        "PROMPT_REQUIRED": "[!] Required field",
        "PROMPT_EMPTY_TO_FINISH": "(empty line to finish):",
    },
    "ru": {
        "TITLE": "ЗАГОЛОВОК",
        "SUBTASKS": "SUBTASKS",
        "SUBTASK_DETAILS": "SUBTASK DETAILS",
        "CRITERIA": "Критерии",
        "TESTS": "Тесты",
        "BLOCKERS": "Блокеры",
        "DESCRIPTION": "Description",
        "BLOCKERS_HEADER": "Blockers",
        "DOMAIN": "Домен",
        "PHASE": "Фаза",
        "COMPONENT": "Компонент",
        "PARENT": "Родитель",
        "DESCRIPTION_MISSING": "Нет описания",
        "PRIORITY": "Приоритет",
        "PROGRESS": "Прогресс",
        "COMPLETED_SUFFIX": "готово",
        "TAGS": "Теги",
        "STATUS_DONE": "ГОТОВО",
        "STATUS_IN_PROGRESS": "В РАБОТЕ",
        "STATUS_BACKLOG": "БЭКЛОГ",
        "CHECKPOINT_CRITERIA": "Критерии",
        "CHECKPOINT_TESTS": "Тесты",
        "CHECKPOINT_BLOCKERS": "Блокеры",
        "LOG_CRITERIA": "Критерии",
        "LOG_TESTS": "Тесты",
        "LOG_BLOCKERS": "Блокеры",
        "DESCRIPTION_PROMPT": "Описание",
        "DOMAIN_LABEL": "Домен",
        "PHASE_LABEL": "Фаза",
        "COMPONENT_LABEL": "Компонент",
        "TAGS_LABEL": "Теги",
        "PARENT_LABEL": "Родитель",
        "BLOCKERS_LABEL": "Блокеры",
        "LANGUAGE_LABEL": "Язык",
        "LANGUAGE_HINT": "Enter — переключить язык (en, ru, uk, es, fr, zh, hi, ar)",
        "CLIPBOARD_EMPTY": "Буфер обмена пуст или недоступен",
        "OPTION_DISABLED": "Опция недоступна",
        "VALUE_NOT_AVAILABLE": "н/д",
        "ERR_TASK_NOT_COMPLETE": "Не все подзадачи завершены (Not all subtasks)",
        "ERR_TASK_NO_CRITERIA_TESTS": "На задаче нет критериев/тестов",
        "ERR_SUBTASK_NO_CRITERIA": "Подзадача {idx} '{title}' без критериев",
        "ERR_SUBTASK_NO_TESTS": "Подзадача {idx} '{title}' без тестов",
        "ERR_SUBTASK_CHECKPOINTS": "Подтверди {items} перед завершением",
        "STATUS_MESSAGE_PUSH_OK": "Git push завершён",
        "STATUS_MESSAGE_PUSH_FAIL": "Push не удался: {error}",
        "STATUS_MESSAGE_BOOTSTRAP_ERROR": "Ошибка git bootstrap: {error}",
        "STATUS_MESSAGE_BOOTSTRAP_FAILED": "Bootstrap не выполнен: {error}",
        "STATUS_MESSAGE_REFRESHED": "Кэш Projects обновлён",
        "STATUS_MESSAGE_OPTION_DISABLED": "Опция недоступна",
        "STATUS_MESSAGE_PAT_MISSING": "PAT не найден",
        "STATUS_MESSAGE_PROMPT_PAT": "Введи PAT для проверки",
        "STATUS_MESSAGE_RATE_LIMIT": "Rate limit: осталось {remaining}; ждать {seconds}s",
        "STATUS_MESSAGE_CLI_UPDATED": "↻ CLI: задачи обновлены (внешние изменения)",
        "STATUS_MESSAGE_AUTO_SYNC": "Auto-sync: {count} задач",
        "STATUS_MESSAGE_LANG_SET": "Язык: {lang}",
        "STATUS_MESSAGE_PAT_SAVED": "PAT сохранён",
        "STATUS_MESSAGE_PAT_CLEARED": "PAT очищен",
        "STATUS_MESSAGE_PROJECT_NUMBER_REQUIRED": "Номер проекта должен быть >0",
        "STATUS_MESSAGE_PROJECT_NUMBER_UPDATED": "Номер проекта обновлён",
        "STATUS_MESSAGE_POOL_INTEGER": "Pool должен быть целым (0=auto)",
        "STATUS_MESSAGE_POOL_UPDATED": "Pool обновлён",
        "STATUS_MESSAGE_CHECKPOINTS_REQUIRED": "Нужно подтвердить checkpoints",
        "STATUS_MESSAGE_PROJECT_OPEN": "Открываю GitHub Project → {url}",
        "STATUS_MESSAGE_OPEN_FAILED": "Не удалось открыть ссылку: {error}",
        "STATUS_MESSAGE_PROJECT_URL_UNAVAILABLE": "URL проекта недоступен",
        "STATUS_MESSAGE_PASTE_PAT": "Вставь PAT (пусто — очистить)",
        "STATUS_MESSAGE_SYNC_ON": "Sync включён",
        "STATUS_MESSAGE_SYNC_OFF": "Sync выключен",
        "STATUS_MESSAGE_VALIDATING": "Проверка...",
        "STATUS_MESSAGE_VALIDATE_LABEL": "Проверяю {label}",
        "ERR_TASK_NOT_FOUND": "Задача {task_id} не найдена (not found)",
        "SETTINGS_NAV_HINT": "Вверх/Вниз — выбрать, Enter — действие, Esc — закрыть",
        "SETTINGS_STATUS_LABEL": "Статус синка",
        "SETTINGS_STATUS_HINT": "Текущее состояние синка",
        "SETTINGS_STATUS_ON": "Sync ВКЛ",
        "SETTINGS_STATUS_OFF": "Sync ВЫКЛ ({reason})",
        "SETTINGS_PAT_LABEL": "GitHub PAT",
        "SETTINGS_PAT_SAVED": "Сохранён (…{preview})",
        "SETTINGS_PAT_ENV": "ENV {env}",
        "SETTINGS_PAT_NOT_SET": "Не задан",
        "SETTINGS_PAT_HINT": "Enter — вставить PAT или очистить",
        "SETTINGS_SYNC_LABEL": "Sync",
        "SETTINGS_SYNC_HINT": "Enter — переключить auto-sync",
        "SETTINGS_SYNC_NO_REMOTE": "Недоступно (нет git remote)",
        "SETTINGS_SYNC_DISABLED": "Выкл",
        "SETTINGS_SYNC_NO_PAT": "Недоступно (нет PAT)",
        "SETTINGS_SYNC_ENABLED": "Вкл",
        "SETTINGS_PROJECT_LABEL": "GitHub Project",
        "SETTINGS_PROJECT_UNAVAILABLE": "недоступно",
        "SETTINGS_BOOTSTRAP_LABEL": "Инициализация git + origin",
        "SETTINGS_BOOTSTRAP_VALUE": "Создать repo и запушить",
        "SETTINGS_BOOTSTRAP_HINT": "Enter — укажи URL (https://github.com/owner/repo.git); выполнит git init/add/push",
        "SETTINGS_PROJECT_URL_LABEL": "Project URL",
        "SETTINGS_PROJECT_URL_HINT": "g — открыть в браузере",
        "SETTINGS_PROJECT_NUMBER_LABEL": "Project number",
        "SETTINGS_PROJECT_NUMBER_HINT": "Enter — обновить номер Project v2",
        "SETTINGS_POOL_LABEL": "Sync pool",
        "SETTINGS_POOL_HINT": "Enter — установить pool (0=auto). Ограничивает API budget.",
        "SETTINGS_LAST_PULL_LABEL": "Последний pull/push",
        "SETTINGS_LAST_PULL_HINT": "Обновляется после успешного синка",
        "SETTINGS_RATE_LABEL": "Rate limit",
        "SETTINGS_RATE_HINT": "GitHub remaining/reset (обновляется после запросов)",
        "SETTINGS_REMOTE_LABEL": "Git remote",
        "SETTINGS_REMOTE_HINT": "Нужен для авто-детекта Projects; меняй через git remote set-url origin",
        "SETTINGS_REFRESH_LABEL": "Reload fields",
        "SETTINGS_REFRESH_VALUE": "Обновить кеш GraphQL",
        "SETTINGS_REFRESH_HINT": "Enter — сброс кеша Projects перед синком",
        "SETTINGS_REFRESH_DISABLED": "Нужен выбранный проект и PAT",
        "SETTINGS_VALIDATE_PAT_LABEL": "Validate PAT",
        "SETTINGS_VALIDATE_PAT_HINT": "Enter — проверить токен через GitHub GraphQL",
        "SETTINGS_VALIDATE_PAT_DISABLED": "Сначала сохрани PAT",
        "LABEL_SUBTASKS_JSON": "JSON массив подзадач",
        "ERR_INVALID_FOLDER": "Некорректная папка",
        "ERR_NO_LAST_TASK": "Нет последней задачи: вызови apply_task show/list/next",
        "ERR_JSON_ARRAY_REQUIRED": "JSON должен быть массивом объектов",
        "ERR_JSON_ELEMENT_OBJECT": "Элемент {idx} должен быть объектом",
        "ERR_JSON_ELEMENT_TITLE": "Элемент {idx} без 'title'",
        "ERR_JSON_ELEMENT_CRITERIA": "Элемент {idx}: нужны критерии",
        "ERR_JSON_ELEMENT_TESTS": "Элемент {idx}: нужны тесты",
        "ERR_JSON_ELEMENT_BLOCKERS": "Элемент {idx}: нужны блокеры/зависимости",
        "ERR_JSON_INVALID": "Некорректный JSON: {error}",
        "ERR_JSON_FORMAT_HINT": "Используй JSON массив. Пример: '[{\"title\":\"Design cache rollout >=20 chars\",\"criteria\":[\"hit ratio >80%\"],\"tests\":[\"pytest -k cache\"],\"blockers\":[\"redis downtime\"]}]'\\nПричина: {error}",
        "ERR_FLAGSHIP_SUBTASKS": "Подзадачи не соответствуют flagship-качеству",
        "PROMPT_ABORTED": "[X] Отмена",
        "PROMPT_REQUIRED": "[!] Обязательное поле",
        "PROMPT_EMPTY_TO_FINISH": "(пустая строка для завершения):",
    },
}
